### ISSUE TITLE
New release for Laravel 10?

### ISSUE THREAD

**Issue by yipeecaiey** [madewithlove/laravel-nova-uuid-support#10]
I'm wondering if there is a reason you haven't released a new version with the changes from laravel shift to support L10?  Of course composer can be set to use the latest commit to the repo...but...?

**Comment by WouterSioen** [comment]
I've made a new tag that includes Laravel 10 support. Thanks for notifying us that we forgot to add the release.

**Comment by yipeecaiey** [comment]
thanks!
