### ISSUE TITLE
On php artisan migrate:reset Warning: 1265 Data truncated for column

### ISSUE THREAD

**Issue by egerb** [madewithlove/laravel-nova-uuid-support#5]
How to reproduce:
1. Run migrations
2. Add any data with nova and try to edit 
3. Try to run php artisan migrate:reset or similar one
Get Warning: 1265 Data truncated for column as action_events filled with string data && can't be safety converted to int.
Conclusion is to remove
`Schema::table('action_events', function (Blueprint $table) {
            $table->integer('actionable_id')->unsigned()->change();
            $table->integer('model_id')->unsigned()->change();
            $table->integer('target_id')->unsigned()->change();
            $table->integer('user_id')->unsigned()->change();
        });`
from down method.

**Comment by WouterSioen** [comment]
Hey @egerb 

This should be fixed with the latest release of this package.

Thanks for the bug report and enjoy the new release.
